sudo: false
language: node_js
node_js:
  - "10"
install:
  - npm install
before_script:
  - npm install
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@latest
script:
  - npm build
notifications:
  email:
    on_success: always
    on_failure: always
