version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

      # Service container image available at `host: localhost`
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: testdb

    steps:
      - checkout

      # Install npm
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"

      # Restore dependencies if they are saved
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      # Install dependendencies
      - run:
          name: install-dependencies
          command: npm install

      # Install postgres sql
      - run: sudo apt install -y postgresql-client || true

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm run build
      - run: npm run migrations
