version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    paralelism: 4
    steps:
      - checkout

      # Install npm
      - run:
          name: Update-npm
          command: "sudo npm install -g npm@5"

      # Restore dependencies if they are saved
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      # Install dependendencies
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Build Project
          command: npm run build
  test:
    docker:
      # Service container image available at `host: localhost`
      - image: circleci/postgres:11.2

        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: testdb

    paralelism: 4
    steps:
      # Install postgres sql
      - run:
          name: Install postgree's server
          command: sudo apt install -y postgresql-client || true

      - run:
          name: Migrate database
          command: npm run migrations
