import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1548891232589 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query("DROP TABLE IF EXISTS heroclass CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS equip CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS adventure CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS monster CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS playstatus CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS inventory_equip CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS inventory_potion CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS hero CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS weapon CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS shield CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS equip CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS potion CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS proficience CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS play_status CASCADE;");
    await queryRunner.query("DROP TABLE IF EXISTS adventure_monsters CASCADE;");

    await queryRunner.query(
      "CREATE TABLE heroclass (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    name CHARACTER(30) NOT NULL," +
        "    damageBuff INTEGER NOT NULL," +
        "    shieldBuff INTEGER NOT NULL," +
        "    hpBuff INTEGER NOT NULL," +
        "    goldBuff INTEGER NOT NULL," +
        "    expBuff INTEGER NOT NULL," +
        "    attackSpeedBuff INTEGER NOT NULL" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE equip(" +
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "name CHARACTER(30) NOT NULL," +
        "level INTEGER NOT NULL," +
        "type CHARACTER(20) NOT NULL," +
        "defence INTEGER," +
        "damage INTEGER," +
        "price INTEGER NOT NULL" +
        "sellprice INTEGER NOT NULL" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE proficience (" +
        "   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    level INTEGER NOT NULL," +
        "    xp INTEGER NOT NULL," +
        "    levelMaxXp INTEGER NOT NULL" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE monster (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    name CHARACTER(30) NOT NULL," +
        "    level INTEGER NOT NULL," +
        "    damage INTEGER NOT NULL," +
        "    hp INTEGER NOT NULL," +
        "    defence INTEGER NOT NULL," +
        "    givedxp INTEGER NOT NULL," +
        "    givedgold INTEGER NOT NULL," +
        "    equipDropChance INTEGER NOT NULL," +
        "    equipDropId BIGINT," +
        "    FOREIGN KEY (equipDropId) REFERENCES Equip(id)" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE potion (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    name CHARACTER(50) NOT NULL," +
        "    price INTEGER NOT NULL," +
        "    sellPrice INTEGER NOT NULL," +
        "    hpheal INTEGER NOT NULL" +
        "    healDefinition CHARACTER(15) NOT NULL" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE adventure (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    level INTEGER NOT NULL," +
        "    name CHARACTER(40) NOT NULL," +
        "    monsterid BIGINT NOT NULL," +
        "    FOREIGN KEY(monsterid) REFERENCES monster(id)" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE play_status (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    task CHARACTER(30)," +
        "    gold INTEGER NOT NULL," +
        "    monsterskilled INTEGER NOT NULL DEFAULT 0," +
        "    exp INTEGER NOT NULL DEFAULT 0," +
        "    timeStarted INTEGER NOT NULL DEFAULT 0," +
        "    adventureId BIGINT NULL," +
        "    FOREIGN KEY (adventureId) REFERENCES adventure(id)" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE hero (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    name CHARACTER(30) NOT NULL," +
        "    level INTEGER NOT NULL," +
        "    hpTotal INTEGER NOT NULL," +
        "    hpActual INTEGER NOT NULL," +
        "    xp INTEGER NOT NULL," +
        "    levelMaxXp INTEGER NOT NULL," +
        "    gold INTEGER NOT NULL," +
        "    deaths INTEGER NOT NULL," +
        "    monstersKilled INTEGER NOT NULL," +
        "    shieldId BIGINT," +
        "    weaponId BIGINT," +
        "    playStatusId BIGINT," +
        "    damageProficienceId BIGINT," +
        "    defenceProficienceId BIGINT," +
        "    heroClassId BIGINT," +
        "    FOREIGN KEY(shieldId) REFERENCES equip(id)," +
        "    FOREIGN KEY(weaponId) REFERENCES equip(id)," +
        "    FOREIGN KEY(playStatusId) REFERENCES play_status(id)," +
        "    FOREIGN KEY(damageProficienceId) REFERENCES proficience(id)," +
        "    FOREIGN KEY(defenceProficienceId) REFERENCES proficience(id)," +
        "    FOREIGN KEY(heroClassId) REFERENCES heroclass(id)" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE inventory_potion (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    heroId BIGINT," +
        "    amount INTEGER NOT NULL," +
        "    potionId BIGINT," +
        "    FOREIGN KEY(potionId) REFERENCES potion(id)," +
        "    FOREIGN KEY(heroId) REFERENCES hero(id)" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE inventory_equip (" +
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "    equiped BOOLEAN NOT NULL," +
        "    equipId BIGINT," +
        "    heroId BIGINT," +
        "    FOREIGN KEY(equipId) REFERENCES equip(id)," +
        "    FOREIGN KEY(heroId) REFERENCES hero(id)" +
        ");"
    );

    await queryRunner.query(
      "CREATE TABLE adventure_monsters" +
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "monsterId BIGINT" +
        "adventureId BIGINT" +
        "FOREIGN KEY(monsterId) REFERENCES monster(id)" +
        "FOREIGN KEY(adventureId) REFERENCES adventure(id)"
    );
  }

  public async down(queryRunner: QueryRunner): Promise<any> {}
}
